# Things to know about numpy 

In [3]:
import numpy as np

## Create in numpy 

In [61]:
data = np.random.rand(3,3,2) ##  npRandom array with
zeroes = np.zeros((2,2,2)) ## zero valued arrays 
full = np.full((2, 2, 2), 7) ## full valued arrays instead of zero it will be 7 or any number you specify
ones = np.ones((2, 2, 2)) ## fills our arrays with one 

In [62]:
data

array([[[0.37396371, 0.9195228 ],
        [0.45446456, 0.8888557 ],
        [0.63441433, 0.3843134 ]],

       [[0.20123346, 0.08295576],
        [0.06475015, 0.58865881],
        [0.43990856, 0.30516933]],

       [[0.80834694, 0.03596264],
        [0.27744156, 0.98372367],
        [0.29511487, 0.09584774]]])

In [28]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [29]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [30]:
# Converting a regular array / list to a numpy array  
import numpy as np
custom_array = [[2, 3],[ 5,3]]
arr = np.array(custom_array)

## Reading Array

In [31]:
# Attribute 
shape = data.shape # the shape of the data
size = data.size # the number of elements in the data
type = data.dtype # the data type of the data

In [32]:
shape

(3, 3, 2)

In [33]:
size

18

In [34]:
type

dtype('float64')

In [37]:
#slicing 
arr2 = data[0] #takes the first data 
slicer = data[0:2] #creates a copy of the first two elements
reverse = data[-1]
singleValue = data[0][0]



In [38]:
data

array([[[0.29558976, 0.55350193],
        [0.80705861, 0.60893379],
        [0.87821737, 0.08860468]],

       [[0.93806142, 0.87380188],
        [0.38483065, 0.02210072],
        [0.61523528, 0.65189245]],

       [[0.89831062, 0.57697108],
        [0.71801226, 0.34482585],
        [0.37539257, 0.85290402]]])

In [36]:
arr2

array([[0.29558976, 0.55350193],
       [0.80705861, 0.60893379],
       [0.87821737, 0.08860468]])

In [39]:
slicer

array([[[0.29558976, 0.55350193],
        [0.80705861, 0.60893379],
        [0.87821737, 0.08860468]],

       [[0.93806142, 0.87380188],
        [0.38483065, 0.02210072],
        [0.61523528, 0.65189245]]])

In [40]:
reverse

array([[0.89831062, 0.57697108],
       [0.71801226, 0.34482585],
       [0.37539257, 0.85290402]])

In [41]:
singleValue

array([0.29558976, 0.55350193])

## Updating 

In [42]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [43]:
list2

array([0.73748883, 0.38423549, 0.05404358, 0.64864031, 0.11140669,
       0.54246164, 0.93034948, 0.90135959, 0.80104821, 0.08397375])

In [47]:
list1

array([0.38138689, 0.4060113 , 0.66664821, 0.48348556, 0.41984489,
       0.76556014, 0.2308085 , 0.04297293, 0.36485646, 0.89918679])

In [45]:
add = np.add(list2, list1)
sub = np.subtract(list2, list1)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [46]:
add

array([1.11887572, 0.79024679, 0.72069179, 1.13212587, 0.53125158,
       1.30802179, 1.16115798, 0.94433253, 1.16590467, 0.98316054])

In [48]:
sub

array([ 0.35610194, -0.0217758 , -0.61260463,  0.16515475, -0.3084382 ,
       -0.2230985 ,  0.69954098,  0.85838666,  0.43619174, -0.81521304])

In [49]:
div

array([ 0.5171426 ,  1.05667306, 12.33538145,  0.74538316,  3.76857864,
        1.41127055,  0.24808795,  0.04767568,  0.45547379, 10.70795082])

In [50]:
mult

array([0.28126857, 0.15600395, 0.03602806, 0.31360822, 0.04677353,
       0.41528701, 0.21473257, 0.03873407, 0.29226762, 0.07550809])

In [51]:
dot

1.870211688519128

In [53]:
# Stat func 
sqrt = np.sqrt(25)  
ab = np.abs(-2) ## get the absolute value so -2 becomes 2
power = np.power(2, 3)
log = np.log(100)
exp  = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [54]:
sqrt

5.0

In [55]:
ab

2

In [65]:
data

array([[[25.        ,  0.9195228 ],
        [ 0.45446456,  0.8888557 ],
        [ 0.63441433,  0.3843134 ]],

       [[ 0.20123346,  0.08295576],
        [ 0.06475015,  0.58865881],
        [ 0.43990856,  0.30516933]],

       [[ 0.80834694,  0.03596264],
        [ 0.27744156,  0.98372367],
        [ 0.29511487,  0.09584774]]])

In [67]:
data[0][0][0] = 700

In [68]:
data

array([[[7.00000000e+02, 9.19522799e-01],
        [4.54464559e-01, 8.88855701e-01],
        [6.34414332e-01, 3.84313403e-01]],

       [[2.01233463e-01, 8.29557609e-02],
        [6.47501528e-02, 5.88658805e-01],
        [4.39908562e-01, 3.05169335e-01]],

       [[8.08346941e-01, 3.59626351e-02],
        [2.77441564e-01, 9.83723673e-01],
        [2.95114872e-01, 9.58477369e-02]]])

In [69]:
data.sort()

In [70]:
data

array([[[9.19522799e-01, 7.00000000e+02],
        [4.54464559e-01, 8.88855701e-01],
        [3.84313403e-01, 6.34414332e-01]],

       [[8.29557609e-02, 2.01233463e-01],
        [6.47501528e-02, 5.88658805e-01],
        [3.05169335e-01, 4.39908562e-01]],

       [[3.59626351e-02, 8.08346941e-01],
        [2.77441564e-01, 9.83723673e-01],
        [9.58477369e-02, 2.95114872e-01]]])

In [71]:
data.np.sort()

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [74]:
np.sort(data)

array([[[9.19522799e-01, 7.00000000e+02],
        [4.54464559e-01, 8.88855701e-01],
        [3.84313403e-01, 6.34414332e-01]],

       [[8.29557609e-02, 2.01233463e-01],
        [6.47501528e-02, 5.88658805e-01],
        [3.05169335e-01, 4.39908562e-01]],

       [[3.59626351e-02, 8.08346941e-01],
        [2.77441564e-01, 9.83723673e-01],
        [9.58477369e-02, 2.95114872e-01]]])

In [76]:
print(data.shape)

(3, 3, 2)


In [78]:
#reshaping
data = data.reshape((2,3,-1)) #the minus means you don't care about the last shape so it can be any depending on it's calculation 

In [79]:
data

array([[[9.19522799e-01, 7.00000000e+02, 4.54464559e-01],
        [8.88855701e-01, 3.84313403e-01, 6.34414332e-01],
        [8.29557609e-02, 2.01233463e-01, 6.47501528e-02]],

       [[5.88658805e-01, 3.05169335e-01, 4.39908562e-01],
        [3.59626351e-02, 8.08346941e-01, 2.77441564e-01],
        [9.83723673e-01, 9.58477369e-02, 2.95114872e-01]]])

In [80]:
print(data.shape)

(2, 3, 3)


In [82]:
zeroes2 = np.zeros((9)) # 9 values of 0 in the list/array
print(zeroes2)
zeroes2 = np.append(zeroes2, [2,3,4]) 
print(zeroes2)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 3. 4.]


In [84]:
# Inserting a value at a specified point 
import numpy as np
zeroes2 = np.insert(zeroes, 1, 1)
zeroes2

array([0., 1., 0., 0., 0., 0., 0., 0., 0.])

## Data

In [85]:
data

array([[[9.19522799e-01, 7.00000000e+02, 4.54464559e-01],
        [8.88855701e-01, 3.84313403e-01, 6.34414332e-01],
        [8.29557609e-02, 2.01233463e-01, 6.47501528e-02]],

       [[5.88658805e-01, 3.05169335e-01, 4.39908562e-01],
        [3.59626351e-02, 8.08346941e-01, 2.77441564e-01],
        [9.83723673e-01, 9.58477369e-02, 2.95114872e-01]]])

In [86]:
np.delete(data , 0, axis=1)

array([[[0.8888557 , 0.3843134 , 0.63441433],
        [0.08295576, 0.20123346, 0.06475015]],

       [[0.03596264, 0.80834694, 0.27744156],
        [0.98372367, 0.09584774, 0.29511487]]])

In [ ]:
np.save('new array', data)